import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useEffect, useMemo, useState } from 'react'
import { api, MinuteDetail, RuleVersion, Segment, Tag } from './api'
import TagSearch from './TagSearch'
import { DisplayZone, formatTime } from './time'
import TrendChart from './TrendChart'

type Props = { segment: Segment; clickedUtc: string; analysisId: number; machineId: number; version: RuleVersion; zone: DisplayZone; liveId?: number; onClose: () => void }
type Classification = { id: number; name: string; active: boolean }

export default function SegmentDetail({ segment, clickedUtc, analysisId, machineId, version, zone, liveId, onClose }: Props) {
  const queryClient = useQueryClient()
  const conditionTags = useMemo(() => [...new Set(version.groups.flatMap((group) => group.conditions.map((item) => item.source_tag_key)))], [version])
  const [displayed, setDisplayed] = useState(segment)
  const [temporary, setTemporary] = useState<Tag[]>([])
  const [lookback, setLookback] = useState(15)
  const [quality, setQuality] = useState(segment.quality_label ?? '')
  const [classificationId, setClassificationId] = useState(segment.classification_id?.toString() ?? '')
  const [note, setNote] = useState(segment.note ?? '')
  const [newClassification, setNewClassification] = useState('')
  const [feedback, setFeedback] = useState('')
  useEffect(() => {
    setDisplayed(segment); setTemporary([]); setQuality(segment.quality_label ?? ''); setClassificationId(segment.classification_id?.toString() ?? ''); setNote(segment.note ?? ''); setNewClassification(''); setFeedback('')
  }, [analysisId, segment])
  const classifications = useQuery({ queryKey: ['classifications', version.id], queryFn: () => api<Classification[]>(`/rule-versions/${version.id}/classifications`) })
  const selectedTags = [...conditionTags, ...temporary.map((tag) => tag.key)]
  const trends = useQuery({ queryKey: ['trends', analysisId, clickedUtc, lookback, selectedTags], queryFn: () => api<any>(`/analyses/${analysisId}/trends?clicked_utc=${encodeURIComponent(clickedUtc)}&lookback_minutes=${lookback}${selectedTags.map((tag) => `&tag_ids=${encodeURIComponent(tag)}`).join('')}`) })
  const minute = useQuery({ queryKey: ['minute', analysisId, clickedUtc], queryFn: () => api<MinuteDetail>(`/analyses/${analysisId}/minutes/${encodeURIComponent(clickedUtc)}`) })
  const latest = useQuery({ queryKey: ['latest', liveId], queryFn: () => api<any>(`/live-sessions/${liveId}/latest`), enabled: Boolean(liveId), refetchInterval: 15_000 })
  const save = useMutation({
    mutationFn: () => api<Segment>(`/segments/${displayed.id}`, { method: 'PATCH', body: JSON.stringify({ quality_label: quality || null, classification_id: classificationId ? Number(classificationId) : null, note: note || null }) }),
    onSuccess: (updated) => { setDisplayed(updated); setQuality(updated.quality_label ?? ''); setClassificationId(updated.classification_id?.toString() ?? ''); setNote(updated.note ?? ''); setFeedback('Segment annotation saved.'); queryClient.invalidateQueries({ queryKey: ['timeline', analysisId] }); queryClient.invalidateQueries({ queryKey: ['minute', analysisId] }) },
    onError: (error) => setFeedback(error.message),
  })
  const createClassification = useMutation({ mutationFn: () => api<Classification>(`/rule-versions/${version.id}/classifications`, { method: 'POST', body: JSON.stringify({ name: newClassification }) }), onSuccess: (created) => { setClassificationId(String(created.id)); setNewClassification(''); queryClient.invalidateQueries({ queryKey: ['classifications', version.id] }) } })
  const removeClassification = useMutation({ mutationFn: (id: number) => api(`/classifications/${id}`, { method: 'DELETE' }), onSuccess: () => { setClassificationId(''); queryClient.invalidateQueries({ queryKey: ['classifications', version.id] }) } })

  return <aside className="fixed inset-y-0 right-0 z-30 w-full max-w-2xl overflow-y-auto border-l border-slate-700 bg-slate-950 p-6 shadow-2xl" aria-label="Segment detail">
    <div className="flex items-start justify-between"><div><p className="text-sm uppercase tracking-wider text-cyan-400">Exact-minute detail</p><h2 className="text-2xl font-bold">{displayed.system_state}</h2></div><button className="button-secondary" onClick={onClose}>Close</button></div>
    <dl className="my-5 grid grid-cols-2 gap-3 rounded-xl bg-slate-900 p-4 text-sm"><div><dt className="text-slate-400">Segment</dt><dd>{formatTime(displayed.start_utc, zone)} – {formatTime(displayed.end_utc, zone)}</dd></div><div><dt className="text-slate-400">Clicked time</dt><dd data-testid="clicked-time">{formatTime(clickedUtc, zone)}</dd></div><div><dt className="text-slate-400">Break reasons</dt><dd>{Object.values(minute.data?.conditions ?? {}).filter((item) => minute.data?.active_condition_ids?.includes(item.condition_id)).map((item) => `${item.display_name} (#${item.condition_id})`).join(', ') || 'None'}</dd></div><div><dt className="text-slate-400">Duration</dt><dd>{Math.round((Date.parse(displayed.end_utc) - Date.parse(displayed.start_utc)) / 60_000)} minutes</dd></div><div><dt className="text-slate-400">Saved classification</dt><dd>{displayed.classification_name || 'None'}</dd></div><div><dt className="text-slate-400">Training</dt><dd>{minute.data?.training_eligible ? 'Eligible' : minute.data?.training_ineligibility_reason ?? 'Not eligible'}</dd></div></dl>
    {['DATA_GAP', 'INSUFFICIENT_HISTORY'].includes(displayed.system_state) && <p className="rounded-lg border border-amber-500 bg-amber-950 p-3 text-amber-100">This system segment can be labeled, but is always excluded from model training.</p>}
    <fieldset className="my-5"><legend className="mb-2 font-semibold">Quality label</legend><div className="flex flex-wrap items-center gap-4">{[['GOOD', '✓ Good'], ['BAD', '✕ Bad'], ['UNSURE', '? Unsure']].map(([value, label]) => <label className="flex-row items-center" key={value}><input type="radio" name="quality" value={value} checked={quality === value} onChange={() => setQuality(value)} /> {label}</label>)}<button type="button" className="button-secondary" onClick={() => setQuality('')}>Clear Label</button></div></fieldset>
    <div className="grid gap-3 md:grid-cols-2"><label>Classification<select aria-label="Classification" value={classificationId} onChange={(event) => setClassificationId(event.target.value)}><option value="">None</option>{classifications.data?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="flex items-end gap-2"><label className="flex-1">New classification<input value={newClassification} onChange={(event) => setNewClassification(event.target.value)} /></label><button className="button-secondary" disabled={!newClassification.trim() || createClassification.isPending} onClick={() => createClassification.mutate()}>Add</button></div>{classificationId && <><button className="button-secondary" type="button" onClick={() => setClassificationId('')}>Clear classification</button><button className="button-secondary text-red-300" disabled={removeClassification.isPending} onClick={() => removeClassification.mutate(Number(classificationId))}>Remove classification from future choices</button></>}</div>
    <label className="my-4">Notes<textarea maxLength={4000} rows={4} value={note} onChange={(event) => setNote(event.target.value)} /></label><div className="flex gap-2"><button className="button-primary" disabled={save.isPending} onClick={() => { setFeedback(''); save.mutate() }}>{save.isPending ? 'Saving…' : 'Save segment label'}</button><button type="button" className="button-secondary" onClick={() => setNote('')}>Clear note</button></div>{feedback && <p role={save.isError ? 'alert' : 'status'} className={save.isError ? 'mt-3 text-red-300' : 'mt-3 text-green-300'}>{feedback}</p>}

    <section className="mt-8 space-y-4"><div className="flex items-end justify-between"><div><h3 className="text-xl font-semibold">Exact evaluation</h3><p className="text-sm text-slate-400">Values and rule state at the clicked minute.</p></div></div>{minute.isLoading && <p>Loading exact minute…</p>}{minute.isError && <p role="alert" className="text-red-300">Exact-minute details are unavailable.</p>}<div className="space-y-2">{Object.values(minute.data?.conditions ?? {}).map((item) => <article className="rounded-lg bg-slate-900 p-3 text-sm" key={item.condition_id}><h4 className="font-semibold">{item.display_name} <span className="text-slate-400">#{item.condition_id}</span></h4><p>Value: {item.value === null ? 'Missing' : String(item.value)} · {item.operator.replaceAll('_', ' ')}</p><p>Raw: {String(item.raw_matched)} · progress {item.pending_progress.current}/{item.pending_progress.required} · qualified {String(item.qualified_active)} · group/root {String(minute.data?.root_expression_result)}</p>{item.delta_reference && <p>Reference: {String(item.delta_reference.value)} at {formatTime(item.delta_reference.minute_utc, zone)}</p>}<p>Quality/status: {item.source?.quality ?? '—'} / {item.source?.status_code ?? '—'}{item.source?.error_text ? ` · ${item.source.error_text}` : ''}</p></article>)}</div><p className="text-sm">Missing tags: {minute.data?.missing_tag_ids?.join(', ') || 'None'}</p></section>

    <section className="mt-8 space-y-4"><div className="flex items-end justify-between"><div><h3 className="text-xl font-semibold">Values and trends</h3><p className="text-sm text-slate-400">Minutes leading up to the exact clicked point.</p></div><label>Lookback minutes<input aria-label="Trend lookback minutes" className="w-28" type="number" min="1" step="1" value={lookback} onChange={(event) => setLookback(Math.max(1, Number(event.target.value)))} /></label></div><div className="grid gap-2 sm:grid-cols-2">{trends.data?.series.map((item: any) => { const point = item.points[item.points.length - 1]; const observed = latest.data?.values.find((value: any) => value.tag_id === item.tag_id); return <article className="rounded-lg bg-slate-900 p-3" key={item.tag_id}><h4 className="font-semibold">{item.display_name}</h4><p>{point?.missing ? 'Missing' : `${point?.value ?? '—'} ${item.units ?? ''}`}</p>{observed && <p className="text-xs text-cyan-300">Latest: {String(observed.value)} at {formatTime(observed.sampled_at_utc, zone)}</p>}{temporary.some((tag) => tag.key === item.tag_id) && <button className="mt-2 text-xs text-red-300" onClick={() => setTemporary((current) => current.filter((tag) => tag.key !== item.tag_id))}>Remove</button>}</article> })}</div><TrendChart series={trends.data?.series ?? []} /><div className="space-y-2">{trends.data?.series.filter((item: any) => item.data_type !== 'numeric').map((item: any) => <article key={item.tag_id} className="rounded-lg border border-slate-700 p-3"><h4 className="font-semibold">{item.display_name} event history</h4><table className="mt-2 w-full text-left text-sm"><thead><tr><th>Minute</th><th>Value</th></tr></thead><tbody>{item.points.map((point: any) => <tr key={point.minute_utc}><td>{formatTime(point.minute_utc, zone)}</td><td>{point.missing ? 'Missing' : String(point.value)}</td></tr>)}</tbody></table></article>)}</div><TagSearch machineId={machineId} label="Add Variable" exclude={selectedTags} onSelect={(tag) => setTemporary((current) => [...current, tag])} /></section>
  </aside>
}
