import { expect, test } from '@playwright/test'

test('real stack create, process, annotate, reload, duplicate, and timezone workflow', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Rule Builder' }).click()
  await page.getByLabel('Machine').selectOption({ label: 'Fixture Line 1' })
  await page.getByLabel('Definition name').fill('Real stack temperature rule')
  await page.getByRole('button', { name: 'Create Draft' }).click()
  const variable = page.getByRole('combobox', { name: 'Variable 1' })
  await variable.fill('Temperature')
  await page.getByRole('option', { name: /Temperature/ }).click()
  await page.getByLabel('Operator 1').selectOption('ABOVE_MAXIMUM')
  await page.getByLabel('Maximum').fill('250')
  await page.getByRole('button', { name: 'Save & Lock Version' }).click()
  await expect(page.getByText(/Version 1 saved and locked/)).toBeVisible()

  await page.getByRole('button', { name: 'Timeline' }).click()
  await page.getByLabel('Timeline machine').selectOption({ label: 'Fixture Line 1' })
  await page.getByLabel('Saved rule version').selectOption({ index: 1 })
  await page.getByLabel('Start minute (UTC)').fill('2026-06-11T19:50')
  await page.getByLabel('Inclusive end minute (UTC)').fill('2026-06-11T20:20')
  await page.getByRole('button', { name: 'Analyze' }).click()
  await expect(page.getByRole('img', { name: /primary and condition timeline lanes/i })).toBeVisible({ timeout: 45_000 })
  await expect(page.getByRole('button', { name: /Unlabeled/ }).first()).toBeVisible()
  await page.getByRole('button', { name: /Unlabeled/ }).first().click()
  await page.getByLabel(/Bad/).check()
  await page.getByLabel('New classification').fill('Real Stack Stop')
  await page.getByRole('button', { name: 'Add' }).click()
  await page.getByLabel('Notes').fill('Persisted through the real API')
  await page.getByRole('button', { name: 'Save segment label' }).click()
  await expect(page.getByText('Segment annotation saved.')).toBeVisible()

  await page.reload()
  await page.getByLabel('Timeline machine').selectOption({ label: 'Fixture Line 1' })
  await page.getByLabel('Saved rule version').selectOption({ index: 1 })
  await page.getByLabel('Load saved analysis').selectOption({ index: 1 })
  await expect(page.getByRole('button', { name: /Bad/ }).first()).toBeVisible({ timeout: 20_000 })
  await page.getByRole('button', { name: /Bad/ }).first().click()
  await expect(page.getByLabel('Notes')).toHaveValue('Persisted through the real API')
  await page.getByRole('button', { name: 'Close' }).click()

  await page.getByLabel('Start minute (UTC)').fill('2026-06-11T19:50')
  await page.getByLabel('Inclusive end minute (UTC)').fill('2026-06-11T20:20')
  await page.getByRole('button', { name: 'Analyze' }).click()
  await expect(page.getByRole('dialog', { name: 'Duplicate analysis' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Open Existing' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Create New' })).toBeVisible()
  await page.getByRole('button', { name: 'Open Existing' }).click()
  await page.getByRole('button', { name: 'Central' }).click()
  await expect(page.getByRole('button', { name: 'Central' })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'UTC', exact: true }).click()
  await expect(page.getByRole('button', { name: 'UTC', exact: true })).toHaveAttribute('aria-pressed', 'true')
})
